#!/usr/bin/ruby

require 'yaml'

yaml_file = nil

	#if the user didn't give me a env default to development
$*[0] = 'development' if $*.size <= 0

	#Look for a config directory
dir = File.dirname(__FILE__)
10.times do 
	puts "#{dir} if #{File.directory?( "#{dir}/config" )}	and #{File.exist?("#{dir}/config/database.yml")}"

			#Track any files we find now
	if File.directory?( "#{dir}/config" )	and File.exist?("#{dir}/config/database.yml")
		yaml_file = "#{dir}/config/database.yml"
	end

		#If we found my yaml file then quit out
	break if !yaml_file.nil?

		#Move back a directory
	dir = "#{dir}/.."
end

	#Quit the program if we didn't find a config file
exit if yaml_file.nil?

	#Load my yaml file
yaml = YAML::load(File.open(yaml_file))

	#load up the requested database now
case yaml[$*[0]]["adapter"]
when "sqlite3"
	exec("sqlite3 #{dir}/#{yaml[$*[0]]["database"]}")
when "mysql"
	exec("mysql -u #{yaml[$*[0]]["username"]} --password=#{yaml[$*[0]]["password"]} #{yaml[$*[0]]["database"]}")
end
